---
editorconfig: Base EditorConfig
black.flake8: flake8 (Black)
black.isort.cfg: isort (Black)
yarn0.gitignore: Gitignore (Yarn Zero-Install)
yarn.gitignore: Gitignore (Yarn Classic)
yarn.gitattributes: Gitattributes (Yarn)
build-go-releases.sh: Build Go Releases
".prettierrc.json": My Prettier Config
