#!/bin/bash
git config --global alias.recommit '!git commit -eF $(git rev-parse --git-dir)/COMMIT_EDITMSG'
git config --global grep.lineNumber true
git config --global core.cleanup scissors
git config --global blame.ignoreRevsFile .git-blame-ignore-revs

# NOTE: Set npm to a placeholder command if it's not installed
if ! command -v npm &> /dev/null; then
	npm() {
		echo "npm is not installed"
	}
fi

npm config set git-tag-version=false

if [ "$CODESPACES" == true ]; then
	npm config set editor=code
	git config --global commit.gpgSign true
	git config --global tag.gpgSign true

	ln -sf $(pwd)/.bin $HOME/bin
else
	# Local-specific setup
	git config --global core.editor nvim
	npm config set editor=nvim

	git config --global diff.external difft
fi
