#!/bin/bash
if [ "$CODESPACES" == true ]; then
	npm config set editor=code
else
	# Local-specific setup
	git config --global core.editor nvim
	npm config set editor=nvim
fi

git config --global alias.recommit '!git commit -eF $(git rev-parse --git-dir)/COMMIT_EDITMSG'
git config --global grep.lineNumber true
npm config set git-tag-version=false
