[icon]
dirs = [
    { name = ".devcontainer",   text = "" },
    { name = ".direnv",         text = "" },
    { name = ".git",            text = "", fg = "red" },
    { name = ".github",         text = "" },
    { name = ".venv",           text = "", fg = "green" },
    { name = ".vscode",         text = "", fg = "cyan" },
    { name = "__pycache__",     text = "", fg = "blue" },
    { name = "Development",     text = "󰴉" },
    { name = "docs",            text = "󰲂", fg = "blue" },
    { name = "node_modules",    text = "", fg = "green" },
    { name = "target",          text = "󱥿", fg = "green" },
    { name = "tmp",             text = "󰪻", fg = "yellow" },
]
exts = [
    # AppImage
    { name = "AppImage", text = "" },

    # Archive files
    { name = "7z",  text = "" },
    { name = "gz",  text = "" },
    { name = "tar", text = "" },
    { name = "zip", text = "" },

    # Backups
    { name = "bak", text = "󰁯" },

    # Batch file
    { name = "bat", text = "", fg = "magenta" },
    { name = "cmd", text = "", fg = "magenta" },

    # C
    { name = "c", text = "", fg = "blue" },
    { name = "h", text = "", fg = "magenta" },
    { name = "o", text = "" },

    # Config files
    { name = "cfg",     text = "" },
    { name = "conf",    text = "" },
    { name = "ini",     text = "" },

    # CSS
    { name = "css", text = "", fg = "blue" },

    # Databases
    { name = "db",      text = "󰆼", fg = "red" },
    { name = "sqlite",  text = "󰆼", fg = "blue" },
    { name = "sqlite3", text = "󰆼", fg = "blue" },

    # Debian packages
    { name = "deb", text = "", fg = "red" },

    # Encrypted files
    { name = "enc", text = "" },

    # Go
    { name = "go", text = "", fg = "cyan" },

    # HTML
    { name = "html", text = "", fg = "red" },

    # Image
    { name = "bmp",     text = "" },
    { name = "gif",     text = "", fg = "green" },
    { name = "ico",     text = "" },
    { name = "jpeg",    text = "", fg = "yellow" },
    { name = "jpg",     text = "", fg = "yellow" },
    { name = "png",     text = "", fg = "blue" },
    { name = "svg",     text = "", fg = "red" },
    { name = "webp",    text = "", fg = "cyan" },

    # JavaScript
    { name = "cjs", text = "", fg = "yellow" },
    { name = "js",  text = "", fg = "yellow" },
    { name = "mjs", text = "", fg = "yellow" },

    # JSON
    { name = "json",    text = "" },
    { name = "jsonc",   text = "" },

    # Lua
    { name = "lua", text = "", fg = "blue" },

    # Markdown
    { name = "md",          text = "", fg = "blue" },
    { name = "markdown",    text = "", fg = "blue" },

    # PowerShell
    { name = "ps1", text = "", fg = "blue" },

    # Python
    { name = "py", text = "", fg = "blue" },

    # Ruby (on Rails)
    { name = "gemspec", text = "", fg = "red" },
    { name = "erb",     text = "", fg = "red" },
    { name = "rb",      text = "", fg = "red" },

    # Rust
    { name = "rs", text = "", fg = "red" },

    # SASS
    { name = "sass", text = "", fg = "magenta" },
    { name = "scss", text = "", fg = "magenta" },

    # Shell
    { name = "bash",    text = "", fg = "magenta" },
    { name = "nu",      text = "", fg = "green" },
    { name = "sh",      text = "", fg = "magenta" },
    { name = "zsh",     text = "", fg = "blue" },

    # Svelte
    { name = "svelte", text = "", fg = "red" },

    # TOML
    { name = "toml", text = "" },

    # TypeScript
    { name = "ts", text = "󰛦", fg = "blue" },

    # Vim
    { name = "vim", text = "", fg = "green" },

    # Vue.js
    { name = "vue", text = "", fg = "green" },

    # YAML
    { name = "yaml",    text = "" },
    { name = "yml",     text = "" },

    # XML
    { name = "xml", text = "󰗀" },
]

files = [
    # All Contributors
    { name = ".all-contributorsrc", text = "", fg = "magenta" },

    # CODEOWNERS
    { name = "CODEOWNERS", text = "󰁥" },

    # Config files
    { name = ".flake8",     text = "" },
    { name = ".inputrc",    text = "" },

    # Clang Format
    { name = ".clang-format", text = "", fg = "yellow" },

    # Devcontainers
    { name = ".devcontainer.json",  text = "" },
    { name = "devcontainer.json",   text = "" },

    # Direnv
    { name = ".envrc", text = "" },

    # Docker
    { name = ".dockerignore",   text = "󰡨", fg = "blue" },
    { name = "Dockerfile",      text = "󰡨", fg = "blue" },

    # Documentation
    { name = "CODE_OF_CONDUCT.md",  text = "" },
    { name = "CONTRIBUTING.md",     text = "" },
    { name = "LICENSE",             text = "" },
    { name = "README",              text = "" },

    # Dotenv
    { name = ".env", text = "" },

    # EditorConfig
    { name = ".editorconfig", text = "" },

    # Git
    { name = ".gitattributes",          text = "", fg = "red" },
    { name = ".gitconfig",              text = "", fg = "red" },
    { name = ".gitignore",              text = "", fg = "red" },
    { name = ".gitkeep",                text = "", fg = "red" },
    { name = ".gitmodules",             text = "", fg = "red" },
    { name = ".git-blame-ignore-revs",  text = "", fg = "red" },
    { name = ".mailmap",                text = "", fg = "red" },

    # GitHub
    { name = "dependabot.yml", text = "", fg = "blue" },

    # Go
    { name = "go.mod",  text = "", fg = "cyan" },
    { name = "go.sum",  text = "", fg = "cyan" },
    { name = "go.work", text = "", fg = "cyan" },

    # Homebrew
    { name = "Brewfile", text = "󰂘" },

    # Makefile
    { name = "Makefile", text = "", fg = "green" },

    # MPV
    { name = "mpv.conf", text = "", fg = "magenta" },

    # nano
    { name = ".nanorc", text = "" },
    { name = "nanorc",  text = "" },

    # Node.js
    { name = ".node-version",   text = "", fg = "green" },
    { name = ".nvmrc",          text = "", fg = "green" },

    # NPM/PNPM/Yarn
    { name = ".npmignore",          text = "", fg = "red" },
    { name = ".npmrc",              text = "", fg = "red" },
    { name = "package.json",        text = "", fg = "red" },
    { name = "package-lock.json",   text = "", fg = "red" },
    { name = "pnpm-lock.yaml",      text = "", fg = "yellow" },
    { name = "pnpm-workspace.yaml", text = "", fg = "yellow" },
    { name = "yarn.lock",           text = "", fg = "blue" },

    # Prettier
    { name = ".prettierignore",     text = "" },
    { name = ".prettierrc.json",    text = "", fg = "yellow" },

    # Python
    { name = "poetry.lock",     text = "", fg = "cyan" },
    { name = "pyproject.toml",  text = "", fg = "cyan" },

    # Ruby (on Rails)
    { name = ".irbrc",          text = "" },
    { name = ".ruby-version",   text = "", fg = "red" },
    { name = "config.ru",       text = "", fg = "red" },
    { name = "Gemfile",         text = "", fg = "blue" },
    { name = "Gemfile.lock",    text = "", fg = "blue" },
    { name = "Rakefile",        text = "", fg = "red" },

    # Rust
    { name = "Cargo.toml", text = "", fg = "yellow" },
    { name = "Cargo.lock", text = "" },

    # Shell
    { name = ".bash_aliases",   text = "", fg = "magenta" },
    { name = ".bashrc",         text = "", fg = "magenta" },
    { name = ".profile",        text = "" },
    { name = ".zshrc",          text = "", fg = "blue" },
    { name = ".zprofile",       text = "", fg = "blue" },

    # Spell checker
    { name = ".cspell.json", text = "󰓆", fg = "green" },

    # TODO
    { name = "TODO",        text = "", fg = "green" },
    { name = "TODO.md",     text = "", fg = "blue" },
    { name = "TODO.txt",    text = "", fg = "green" },

    # TypeScript
    { name = "tsconfig.json", text = "󰛦", fg = "blue" },

    # Vim
    { name = ".vimrc", text = "", fg = "green" },
]

globs = [
    # Docker
    { name = "**/Dockerfile.*", text = "󰡨", fg = "blue" },

    # Documentation
    { name = "**/LICENSE-*",    text = "" },
    { name = "**/README.*",     text = "" },

    # Dotenv
    { name = "**/.env.*", text = "" },

    # GitHub
    { name = "**/.github/workflows/*.{yaml,yml}", text = "", fg = "blue" },

    # Makefile
    { name = "**/Makefile.*", text = "", fg = "green" },

    # TypeScript
    { name = "**/tsconfig.*.json", text = "󰛦", fg = "blue" },
]
